#!/usr/bin/env python

import sys, time, os
from daemon import Daemon

class MyDaemon(Daemon):

    def run(self):
    #	print "LLamada a run()"
        while True :
            self.hour_exec = [0]
            horaActual = time.localtime().tm_hour
            file("/tmp/buildd.log","a+").write("%s> ...\n" % (horaActual))

#			if time.localtime().tm_hour in self.hour_exec :
            if horaActual in self.hour_exec :
                os.system("i386 /root/builder/bin/build.sh")
            #	fic = open("/tmp/buildd.log",'a+')
            #	fic.write("%s> BUILDD: ALERTA! Lanzada generacion de paquetes...\n",time.strftime("%Y/%m/%d.%H:%M:%S",time.localtime()))
            #	fic.close()
            #	file("/tmp/buildd.log","a+").write("%s> BUILDD: ALERTA!! Lanzada generacion de paquetes...\n" % (time.strftime("%Y/%m/%d.%H:%M:%S",time.localtime()))).flush()
                file("/tmp/buildd.log","a+").write("\n> BUILDD: ALERTA!! Lanzada generacion de paquetes...\n")
                time.sleep(3660)
            else:
            #	fic = open("/tmp/buildd.log",'a+')
            #	fic.write("%s> BUILDD: Todavia no es la hora de la Generacion :o)\n",time.strftime("%Y/%m/%d.%H:%M:%S",time.localtime()))
            #	fic.close()
            #	file("/tmp/buildd.log","a+").write("%s> BUILDD: Todavia no es la hora de la Generacion :o)\n" % (time.strftime("%Y/%m/%d.%H:%M:%S",time.localtime()))).flush()
            #	file("/tmp/buildd.log","a+").write(".")
                time.sleep(600)
            #self.min_exec = [35]
            #if time.localtime().tm_min in self.min_exec :
            #	os.system("i386 /root/builder/bin/build.sh")
            #	time.sleep(61)
            #else:
            #	time.sleep(15)

if __name__ == "__main__":
    daemon = MyDaemon('/tmp/buildd.pid')
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            print "Caso del start"
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)
